from pathlib import Path
import pandas as pd


ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT_DIR / "data" / "raw"
DOCS_DIR = ROOT_DIR / "docs"

DOCS_DIR.mkdir(parents=True, exist_ok=True)


def read_csv_safely(file_path: Path) -> pd.DataFrame:
    """
    Try multiple encodings to avoid CSV reading errors.
    """
    encodings = ["utf-8", "utf-8-sig", "latin1"]

    last_error = None
    for encoding in encodings:
        try:
            return pd.read_csv(file_path, encoding=encoding, low_memory=False)
        except Exception as e:
            last_error = e

    raise RuntimeError(f"Failed to read {file_path.name}: {last_error}")


def get_expected_key_columns(file_name: str):
    """
    Define expected business keys for Olist dataset.
    These are used only for basic duplicate checks.
    """
    mapping = {
        "olist_customers_dataset.csv": ["customer_id"],
        "olist_orders_dataset.csv": ["order_id"],
        "olist_products_dataset.csv": ["product_id"],
        "olist_sellers_dataset.csv": ["seller_id"],
        "olist_order_reviews_dataset.csv": ["review_id"],
        "olist_order_payments_dataset.csv": ["order_id", "payment_sequential"],
        "olist_order_items_dataset.csv": ["order_id", "order_item_id"],
        "product_category_name_translation.csv": ["product_category_name"],
    }

    return mapping.get(file_name, [])


def profile_one_file(file_path: Path):
    df = read_csv_safely(file_path)

    file_name = file_path.name
    row_count = len(df)
    column_count = len(df.columns)
    full_row_duplicates = df.duplicated().sum()

    expected_keys = get_expected_key_columns(file_name)
    existing_keys = [col for col in expected_keys if col in df.columns]

    if existing_keys:
        key_duplicates = df.duplicated(subset=existing_keys).sum()
    else:
        key_duplicates = None

    missing_rows = []

    for col in df.columns:
        missing_count = int(df[col].isna().sum())
        missing_rate = round(missing_count / row_count, 4) if row_count > 0 else 0

        missing_rows.append(
            {
                "table_name": file_name.replace(".csv", ""),
                "column_name": col,
                "dtype": str(df[col].dtype),
                "missing_count": missing_count,
                "missing_rate": missing_rate,
                "unique_count": int(df[col].nunique(dropna=True)),
            }
        )

    summary = {
        "file_name": file_name,
        "table_name": file_name.replace(".csv", ""),
        "row_count": row_count,
        "column_count": column_count,
        "full_row_duplicates": int(full_row_duplicates),
        "key_columns": ",".join(existing_keys) if existing_keys else "",
        "key_duplicates": "" if key_duplicates is None else int(key_duplicates),
    }

    sample_data = df.head(5)

    return summary, missing_rows, sample_data


def generate_markdown_report(summaries, missing_detail, samples):
    output_path = DOCS_DIR / "raw_data_profile.md"

    with output_path.open("w", encoding="utf-8") as f:
        f.write("# Raw Data Profiling Report\n\n")
        f.write("This report is automatically generated by `scripts/check_raw_data.py`.\n\n")

        f.write("## 1. Dataset Summary\n\n")
        f.write("| File | Rows | Columns | Full Row Duplicates | Key Columns | Key Duplicates |\n")
        f.write("|---|---:|---:|---:|---|---:|\n")

        for item in summaries:
            f.write(
                f"| {item['file_name']} "
                f"| {item['row_count']} "
                f"| {item['column_count']} "
                f"| {item['full_row_duplicates']} "
                f"| {item['key_columns']} "
                f"| {item['key_duplicates']} |\n"
            )

        f.write("\n## 2. Missing Value Summary\n\n")

        missing_df = pd.DataFrame(missing_detail)
        high_missing_df = missing_df[missing_df["missing_count"] > 0].sort_values(
            by=["table_name", "missing_rate"], ascending=[True, False]
        )

        if high_missing_df.empty:
            f.write("No missing values found.\n\n")
        else:
            f.write("| Table | Column | Dtype | Missing Count | Missing Rate | Unique Count |\n")
            f.write("|---|---|---|---:|---:|---:|\n")

            for _, row in high_missing_df.iterrows():
                f.write(
                    f"| {row['table_name']} "
                    f"| {row['column_name']} "
                    f"| {row['dtype']} "
                    f"| {row['missing_count']} "
                    f"| {row['missing_rate']} "
                    f"| {row['unique_count']} |\n"
                )

        f.write("\n## 3. Sample Records\n\n")

        for file_name, sample_df in samples.items():
            f.write(f"### {file_name}\n\n")
            f.write(sample_df.to_markdown(index=False))
            f.write("\n\n")

    print(f"[OK] Markdown report generated: {output_path}")


def main():
    csv_files = sorted(RAW_DIR.glob("*.csv"))

    if not csv_files:
        raise FileNotFoundError(
            f"No CSV files found in {RAW_DIR}. Please put raw CSV files into data/raw/ first."
        )

    summaries = []
    missing_detail = []
    samples = {}

    for file_path in csv_files:
        print(f"[INFO] Profiling {file_path.name} ...")

        summary, missing_rows, sample_data = profile_one_file(file_path)

        summaries.append(summary)
        missing_detail.extend(missing_rows)
        samples[file_path.name] = sample_data

    summary_df = pd.DataFrame(summaries)
    missing_df = pd.DataFrame(missing_detail)

    summary_path = DOCS_DIR / "raw_data_summary.csv"
    missing_path = DOCS_DIR / "raw_missing_values.csv"

    summary_df.to_csv(summary_path, index=False, encoding="utf-8-sig")
    missing_df.to_csv(missing_path, index=False, encoding="utf-8-sig")

    generate_markdown_report(summaries, missing_detail, samples)

    print(f"[OK] Summary CSV generated: {summary_path}")
    print(f"[OK] Missing value CSV generated: {missing_path}")
    print("[DONE] Raw data profiling completed.")


if __name__ == "__main__":
    main()